### ISSUE TITLE
break interval arithmetic tutorial in smaller tutorials

### ISSUE THREAD

**Issue by lucaferranti** [JuliaIntervals/JuliaIntervalsWebPage#5]
The current [IntervalArithmetic.jl tutorial](https://juliaintervals.github.io/pages/tutorials/tutorialArithmetic/) is overwhelming. It should be broken into smaller tutorials and have more pictures. The last parts (rounding modes and precision) are more advanced and not relevant for a beginner, they should be in an separate "advanced options" section.

**Comment by dpsanders** [comment]
Agreed on all points!
