### ISSUE TITLE
rewrite webpage using Pluto

### ISSUE THREAD

**Issue by lucaferranti** [JuliaIntervals/JuliaIntervalsWebPage#6]
As Pluto, Literate, Franklin integrations are maturing, it might be cool to restructure the webpage using Pluto. I think there are two options

1) use Literate.jl to generate both Pluto and jupyter notebook and allow the user to download whatever they want. This would be the easiest
2) do something like the computational thinking site, would require more work, but might boost the site quality.

**Comment by dpsanders** [comment]
An interactive page would be great! It would be nice to generate the interactive notebooks from Literate if possible.
