### ISSUE TITLE
current section on interval constructors may be misleading

### ISSUE THREAD

**Issue by lucaferranti** [JuliaIntervals/JuliaIntervalsWebPage#7]
The current section on constructors does not take any position about what constructor is preferred. This combined with the part about rounding gives the misleading idea that `@interval` is preferred.

**Comment by dpsanders** [comment]
We should remove *all* references to `@interval`, except in the context of

`@interval <an expression>` 

which is now the only use case, e.g.

`@interval sin(0.1) + cos(0.3)`

Its purpose is to wrap the literals into intervals.
